to handle Email
	GenericFunctions.ClickEvent "text","Email address","Center"
	GenericFunctions.TextEntry "eggplant.techacc@gmail.com"
	set the searchrectangle to fullscreen
end Email

to handle Password
	GenericFunctions.ClickEvent "text","Password","Center"
	GenericFunctions.TextEntry "3ggPl4nt-6sh"
	set the searchrectangle to fullscreen
end Password

to handle SignIn
	GenericFunctions.ClickEvent "Image","Icons/Signin","Center"
end SignIn
